
import java.io.File;
import java.io.FileInputStream;
import java.io.FileOutputStream;
import java.io.ObjectInputStream;
import java.io.ObjectOutputStream;
import java.util.ArrayList;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JComboBox;
import javax.swing.JDialog;
import javax.swing.JOptionPane;
import org.graphstream.graph.*;
import org.graphstream.graph.implementations.*;
import org.graphstream.algorithm.*;
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author manuel
 */
public class Principal extends javax.swing.JFrame {

    /**
     * Creates new form Principal
     */
    public Principal() {
        initComponents();
        listaGeneral = new Listas();
        hospitales = new ArrayList();
        ambulancias = new ArrayList();
        paramedicos = new ArrayList();
        ubicaciones = new ArrayList();
        cargar();
        //this.setExtendedState(MAXIMIZED_BOTH);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jd_gestionRecursos = new javax.swing.JDialog();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jButton6 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jd_creacion = new javax.swing.JDialog();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        tf_nombreHospital = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        tf_direccionHospital = new javax.swing.JTextField();
        js_maxParamedicosHosp = new javax.swing.JSpinner();
        jLabel10 = new javax.swing.JLabel();
        cb_rankingHospital = new javax.swing.JComboBox();
        bt_crearHospital = new javax.swing.JButton();
        js_maxAmbulanciasHosp = new javax.swing.JSpinner();
        jLabel11 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        tf_placaAmbulancia = new javax.swing.JTextField();
        tf_año_ambulancia = new javax.swing.JTextField();
        tf_speedAmbulancia = new javax.swing.JTextField();
        cb_complejosAmbulancia = new javax.swing.JComboBox();
        jLabel15 = new javax.swing.JLabel();
        bt_crearAmbulancia = new javax.swing.JButton();
        jLabel16 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        tf_nombreParamedico = new javax.swing.JTextField();
        tf_edadParamedico = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        jButton7 = new javax.swing.JButton();
        tf_idParamedico = new javax.swing.JTextField();
        cb_rankingParamedico = new javax.swing.JComboBox();
        cb_complejoParamedico = new javax.swing.JComboBox();
        jLabel23 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel55 = new javax.swing.JLabel();
        jd_eliminacion = new javax.swing.JDialog();
        jLabel22 = new javax.swing.JLabel();
        jTabbedPane2 = new javax.swing.JTabbedPane();
        jPanel4 = new javax.swing.JPanel();
        jLabel24 = new javax.swing.JLabel();
        cb_eliminarComplejos = new javax.swing.JComboBox();
        bt_eliminarComplejos = new javax.swing.JButton();
        jLabel25 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jLabel26 = new javax.swing.JLabel();
        cb_eliminarAmbulancias = new javax.swing.JComboBox();
        bt_eliminarAmbulacnias = new javax.swing.JButton();
        jLabel27 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jLabel28 = new javax.swing.JLabel();
        cb_eliminarParamedicos = new javax.swing.JComboBox();
        bt_eliminarParamedicos = new javax.swing.JButton();
        jLabel29 = new javax.swing.JLabel();
        jLabel56 = new javax.swing.JLabel();
        jd_reasignacion = new javax.swing.JDialog();
        jLabel30 = new javax.swing.JLabel();
        jTabbedPane3 = new javax.swing.JTabbedPane();
        jPanel7 = new javax.swing.JPanel();
        jLabel31 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        cb_seleccionarAmbulancia = new javax.swing.JComboBox();
        cb_complejosA = new javax.swing.JComboBox();
        bt_seleccionarAmbulancia = new javax.swing.JButton();
        bt_reasignarAmbulancia = new javax.swing.JButton();
        jLabel33 = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        jLabel34 = new javax.swing.JLabel();
        jLabel35 = new javax.swing.JLabel();
        cb_seleccionarParamedicos = new javax.swing.JComboBox();
        cb_complejosP = new javax.swing.JComboBox();
        bt_seleccionarParamedico = new javax.swing.JButton();
        bt_reasignarParamedico = new javax.swing.JButton();
        jLabel36 = new javax.swing.JLabel();
        jLabel57 = new javax.swing.JLabel();
        jd_menuMapa = new javax.swing.JDialog();
        bt_addUbicaciones = new javax.swing.JButton();
        bt_addConexiones = new javax.swing.JButton();
        jLabel37 = new javax.swing.JLabel();
        bt_dibujar = new javax.swing.JButton();
        jLabel48 = new javax.swing.JLabel();
        jd_addUbicacion = new javax.swing.JDialog();
        jTabbedPane4 = new javax.swing.JTabbedPane();
        jPanel9 = new javax.swing.JPanel();
        cb_complejosMapa = new javax.swing.JComboBox();
        jLabel39 = new javax.swing.JLabel();
        bt_addToMap = new javax.swing.JButton();
        jLabel51 = new javax.swing.JLabel();
        jPanel10 = new javax.swing.JPanel();
        jLabel40 = new javax.swing.JLabel();
        tf_nombreUbicacion = new javax.swing.JTextField();
        tf_DireccionUbicacion = new javax.swing.JTextField();
        bt_agregarUbi = new javax.swing.JButton();
        jLabel41 = new javax.swing.JLabel();
        jLabel52 = new javax.swing.JLabel();
        jLabel38 = new javax.swing.JLabel();
        jLabel50 = new javax.swing.JLabel();
        jLabel49 = new javax.swing.JLabel();
        jd_conexiones = new javax.swing.JDialog();
        jLabel42 = new javax.swing.JLabel();
        cb_ubicacionesConexion = new javax.swing.JComboBox();
        bt_seleccionarUbicacion = new javax.swing.JButton();
        jLabel43 = new javax.swing.JLabel();
        jLabel44 = new javax.swing.JLabel();
        js_km = new javax.swing.JSpinner();
        bt_crearConexion = new javax.swing.JButton();
        jLabel53 = new javax.swing.JLabel();
        jd_emergencias = new javax.swing.JDialog();
        jLabel46 = new javax.swing.JLabel();
        jLabel45 = new javax.swing.JLabel();
        cb_lugarEmergencia = new javax.swing.JComboBox();
        jLabel47 = new javax.swing.JLabel();
        bt_sendEemergency = new javax.swing.JButton();
        cb_rankEemergencia = new javax.swing.JComboBox();
        jLabel54 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        bt_Gestionar = new javax.swing.JButton();
        bt_mapa = new javax.swing.JButton();
        bt_emergencias = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        jd_gestionRecursos.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton4.setBackground(java.awt.Color.gray);
        jButton4.setForeground(new java.awt.Color(155, 11, 11));
        jButton4.setText("Crear Recursos");
        jButton4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton4MouseClicked(evt);
            }
        });
        jd_gestionRecursos.getContentPane().add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 80, 232, 108));

        jButton5.setBackground(java.awt.Color.gray);
        jButton5.setForeground(new java.awt.Color(155, 11, 11));
        jButton5.setText("Eliminar Recursos");
        jButton5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton5MouseClicked(evt);
            }
        });
        jd_gestionRecursos.getContentPane().add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 220, 232, 108));

        jLabel2.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(155, 11, 11));
        jLabel2.setText("Gestion de Recursos");
        jd_gestionRecursos.getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, 20));

        jButton6.setBackground(java.awt.Color.gray);
        jButton6.setForeground(new java.awt.Color(155, 11, 11));
        jButton6.setText("Reasignar Recursos");
        jButton6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton6MouseClicked(evt);
            }
        });
        jd_gestionRecursos.getContentPane().add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 360, 232, 108));

        jLabel4.setIcon(new javax.swing.ImageIcon("/home/manuel/Documentos/estructuraDeDatos/Proyecto4_ED/Hospital_Escuela/Imagenes/54e6d48f7a9fe4ec3dbeabfa7e230a74.jpg")); // NOI18N
        jd_gestionRecursos.getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 730, 550));

        jd_creacion.setBackground(java.awt.Color.darkGray);
        jd_creacion.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTabbedPane1.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jTabbedPane1StateChanged(evt);
            }
        });

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel7.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        jLabel7.setForeground(java.awt.Color.red);
        jLabel7.setText("Direccion");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 130, -1, -1));

        jLabel8.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        jLabel8.setForeground(java.awt.Color.red);
        jLabel8.setText("Capacidad Maxima de Paramedicos");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 180, -1, -1));

        jLabel9.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        jLabel9.setForeground(java.awt.Color.red);
        jLabel9.setText("Capacidad Maxima de Ambulancias");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 220, -1, -1));
        jPanel1.add(tf_nombreHospital, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 70, 289, -1));

        jLabel6.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        jLabel6.setForeground(java.awt.Color.red);
        jLabel6.setText("Nombre");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 60, -1, 34));
        jPanel1.add(tf_direccionHospital, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 130, 286, -1));
        jPanel1.add(js_maxParamedicosHosp, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 180, -1, -1));

        jLabel10.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        jLabel10.setForeground(java.awt.Color.red);
        jLabel10.setText("Grado Maximo de Emergencia");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 270, -1, -1));

        cb_rankingHospital.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "A", "B", "C", "D" }));
        jPanel1.add(cb_rankingHospital, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 270, -1, -1));

        bt_crearHospital.setText("Crear");
        bt_crearHospital.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bt_crearHospitalMouseClicked(evt);
            }
        });
        jPanel1.add(bt_crearHospital, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 330, 109, 64));
        jPanel1.add(js_maxAmbulanciasHosp, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 220, -1, -1));

        jLabel11.setIcon(new javax.swing.ImageIcon("/home/manuel/Documentos/estructuraDeDatos/Proyecto4_ED/Hospital_Escuela/Imagenes/water-cityscapes-architecture-buildings-grayscale-monochrome-lakes-high-quality-background-79484.jpg")); // NOI18N
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 640, 430));

        jTabbedPane1.addTab("Complejos Hospitalarios", jPanel1);

        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel12.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        jLabel12.setForeground(java.awt.Color.red);
        jLabel12.setText("Numero de Placa");
        jPanel2.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(88, 87, -1, -1));

        jLabel13.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        jLabel13.setForeground(java.awt.Color.red);
        jLabel13.setText("Año");
        jPanel2.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(88, 150, -1, -1));

        jLabel14.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        jLabel14.setForeground(java.awt.Color.red);
        jLabel14.setText("Velocidad Maxima km/h");
        jPanel2.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 220, -1, -1));
        jPanel2.add(tf_placaAmbulancia, new org.netbeans.lib.awtextra.AbsoluteConstraints(267, 82, 212, -1));
        jPanel2.add(tf_año_ambulancia, new org.netbeans.lib.awtextra.AbsoluteConstraints(267, 140, 212, -1));
        jPanel2.add(tf_speedAmbulancia, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 220, 160, -1));

        jPanel2.add(cb_complejosAmbulancia, new org.netbeans.lib.awtextra.AbsoluteConstraints(269, 288, 110, -1));

        jLabel15.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        jLabel15.setForeground(java.awt.Color.red);
        jLabel15.setText("Complejo");
        jPanel2.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(88, 293, -1, -1));

        bt_crearAmbulancia.setText("Crear Ambulancia");
        bt_crearAmbulancia.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bt_crearAmbulanciaMouseClicked(evt);
            }
        });
        jPanel2.add(bt_crearAmbulancia, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 360, -1, -1));

        jLabel16.setIcon(new javax.swing.ImageIcon("/home/manuel/Documentos/estructuraDeDatos/Proyecto4_ED/Hospital_Escuela/Imagenes/image.php.png")); // NOI18N
        jPanel2.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 640, 430));

        jTabbedPane1.addTab("Ambulancias", jPanel2);

        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel17.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        jLabel17.setForeground(java.awt.Color.red);
        jLabel17.setText("Nombre ");
        jPanel3.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(89, 56, 140, -1));

        jLabel18.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        jLabel18.setForeground(java.awt.Color.red);
        jLabel18.setText("Edad");
        jPanel3.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(89, 112, -1, -1));

        jLabel19.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        jLabel19.setForeground(java.awt.Color.red);
        jLabel19.setText("Identidad");
        jPanel3.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(89, 180, -1, -1));

        jLabel20.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        jLabel20.setForeground(java.awt.Color.red);
        jLabel20.setText("Ranking");
        jPanel3.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(89, 265, -1, -1));
        jPanel3.add(tf_nombreParamedico, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 50, 251, -1));
        jPanel3.add(tf_edadParamedico, new org.netbeans.lib.awtextra.AbsoluteConstraints(218, 112, 251, -1));

        jLabel21.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        jLabel21.setForeground(java.awt.Color.red);
        jLabel21.setText("Complejo");
        jPanel3.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(327, 265, -1, -1));

        jButton7.setText("Crear Paramedico");
        jButton7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton7MouseClicked(evt);
            }
        });
        jPanel3.add(jButton7, new org.netbeans.lib.awtextra.AbsoluteConstraints(89, 372, -1, -1));
        jPanel3.add(tf_idParamedico, new org.netbeans.lib.awtextra.AbsoluteConstraints(218, 175, 251, -1));

        cb_rankingParamedico.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "A", "B", "C", "D" }));
        jPanel3.add(cb_rankingParamedico, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 260, -1, -1));

        jPanel3.add(cb_complejoParamedico, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 260, 120, -1));

        jLabel23.setIcon(new javax.swing.ImageIcon("/home/manuel/Documentos/estructuraDeDatos/Proyecto4_ED/Hospital_Escuela/Imagenes/image.php.png")); // NOI18N
        jPanel3.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 640, 440));

        jTabbedPane1.addTab("Paramedicos", jPanel3);

        jd_creacion.getContentPane().add(jTabbedPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, 643, 440));

        jLabel5.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(155, 11, 11));
        jLabel5.setText("Creacion de Recursos");
        jd_creacion.getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(217, 26, 222, -1));

        jLabel55.setIcon(new javax.swing.ImageIcon("/home/manuel/Documentos/estructuraDeDatos/Proyecto4_ED/Hospital_Escuela/Imagenes/dark_triangles_by_pixelperf3ct-d6tpizs.png")); // NOI18N
        jd_creacion.getContentPane().add(jLabel55, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 660, 510));

        jd_eliminacion.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel22.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(155, 11, 11));
        jLabel22.setText("Eliminar Recursos");
        jd_eliminacion.getContentPane().add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(163, 12, -1, -1));

        jTabbedPane2.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jTabbedPane2StateChanged(evt);
            }
        });

        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel24.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        jLabel24.setForeground(java.awt.Color.red);
        jLabel24.setText("Complejos Hospitalarios");
        jPanel4.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(46, 74, -1, -1));

        jPanel4.add(cb_eliminarComplejos, new org.netbeans.lib.awtextra.AbsoluteConstraints(56, 110, 128, -1));

        bt_eliminarComplejos.setText("Eliminar");
        bt_eliminarComplejos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bt_eliminarComplejosMouseClicked(evt);
            }
        });
        jPanel4.add(bt_eliminarComplejos, new org.netbeans.lib.awtextra.AbsoluteConstraints(244, 109, -1, -1));

        jLabel25.setIcon(new javax.swing.ImageIcon("/home/manuel/Documentos/estructuraDeDatos/Proyecto4_ED/Hospital_Escuela/Imagenes/water-cityscapes-architecture-buildings-grayscale-monochrome-lakes-high-quality-background-79484.jpg")); // NOI18N
        jPanel4.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 500, 350));

        jTabbedPane2.addTab("Complejos Hospitalarios", jPanel4);

        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel26.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        jLabel26.setForeground(java.awt.Color.red);
        jLabel26.setText("Ambulancias");
        jPanel5.add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(74, 83, -1, -1));

        jPanel5.add(cb_eliminarAmbulancias, new org.netbeans.lib.awtextra.AbsoluteConstraints(74, 117, 130, -1));

        bt_eliminarAmbulacnias.setText("Eliminar");
        bt_eliminarAmbulacnias.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bt_eliminarAmbulacniasMouseClicked(evt);
            }
        });
        jPanel5.add(bt_eliminarAmbulacnias, new org.netbeans.lib.awtextra.AbsoluteConstraints(305, 116, 101, -1));

        jLabel27.setIcon(new javax.swing.ImageIcon("/home/manuel/Documentos/estructuraDeDatos/Proyecto4_ED/Hospital_Escuela/Imagenes/image.php.png")); // NOI18N
        jPanel5.add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 500, 350));

        jTabbedPane2.addTab("Ambulancias", jPanel5);

        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel28.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        jLabel28.setForeground(java.awt.Color.red);
        jLabel28.setText("Paramedicos");
        jPanel6.add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(58, 80, -1, -1));

        jPanel6.add(cb_eliminarParamedicos, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 120, 131, -1));

        bt_eliminarParamedicos.setText("Eliminar");
        bt_eliminarParamedicos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bt_eliminarParamedicosMouseClicked(evt);
            }
        });
        jPanel6.add(bt_eliminarParamedicos, new org.netbeans.lib.awtextra.AbsoluteConstraints(289, 119, -1, -1));

        jLabel29.setIcon(new javax.swing.ImageIcon("/home/manuel/Documentos/estructuraDeDatos/Proyecto4_ED/Hospital_Escuela/Imagenes/image.php.png")); // NOI18N
        jPanel6.add(jLabel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 500, 350));

        jTabbedPane2.addTab("Paramedicos", jPanel6);

        jd_eliminacion.getContentPane().add(jTabbedPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 39, -1, -1));

        jLabel56.setIcon(new javax.swing.ImageIcon("/home/manuel/Documentos/estructuraDeDatos/Proyecto4_ED/Hospital_Escuela/Imagenes/dark_triangles_by_pixelperf3ct-d6tpizs.png")); // NOI18N
        jd_eliminacion.getContentPane().add(jLabel56, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 510, 370));

        jd_reasignacion.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel30.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        jLabel30.setForeground(new java.awt.Color(155, 11, 11));
        jLabel30.setText("Reasignacion de Recursos");
        jd_reasignacion.getContentPane().add(jLabel30, new org.netbeans.lib.awtextra.AbsoluteConstraints(178, 23, -1, -1));

        jTabbedPane3.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jTabbedPane3StateChanged(evt);
            }
        });

        jPanel7.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel31.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        jLabel31.setForeground(java.awt.Color.red);
        jLabel31.setText("Ambulancias");
        jPanel7.add(jLabel31, new org.netbeans.lib.awtextra.AbsoluteConstraints(48, 32, -1, -1));

        jLabel32.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        jLabel32.setForeground(java.awt.Color.red);
        jLabel32.setText("Complejo");
        jPanel7.add(jLabel32, new org.netbeans.lib.awtextra.AbsoluteConstraints(59, 131, -1, -1));

        jPanel7.add(cb_seleccionarAmbulancia, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 30, 155, -1));

        jPanel7.add(cb_complejosA, new org.netbeans.lib.awtextra.AbsoluteConstraints(181, 126, 155, -1));

        bt_seleccionarAmbulancia.setText("Seleccionar");
        bt_seleccionarAmbulancia.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bt_seleccionarAmbulanciaMouseClicked(evt);
            }
        });
        jPanel7.add(bt_seleccionarAmbulancia, new org.netbeans.lib.awtextra.AbsoluteConstraints(381, 26, -1, -1));

        bt_reasignarAmbulancia.setText("Reasignar");
        bt_reasignarAmbulancia.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bt_reasignarAmbulanciaMouseClicked(evt);
            }
        });
        jPanel7.add(bt_reasignarAmbulancia, new org.netbeans.lib.awtextra.AbsoluteConstraints(395, 125, -1, -1));

        jLabel33.setIcon(new javax.swing.ImageIcon("/home/manuel/Documentos/estructuraDeDatos/Proyecto4_ED/Hospital_Escuela/Imagenes/image.php.png")); // NOI18N
        jPanel7.add(jLabel33, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 520, 250));

        jTabbedPane3.addTab("Ambulancias", jPanel7);

        jPanel8.setForeground(java.awt.Color.red);
        jPanel8.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel34.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        jLabel34.setForeground(java.awt.Color.red);
        jLabel34.setText("Paramedicos");
        jPanel8.add(jLabel34, new org.netbeans.lib.awtextra.AbsoluteConstraints(49, 54, -1, -1));

        jLabel35.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        jLabel35.setForeground(java.awt.Color.red);
        jLabel35.setText("Complejo");
        jPanel8.add(jLabel35, new org.netbeans.lib.awtextra.AbsoluteConstraints(49, 140, -1, -1));

        jPanel8.add(cb_seleccionarParamedicos, new org.netbeans.lib.awtextra.AbsoluteConstraints(195, 52, 146, -1));

        jPanel8.add(cb_complejosP, new org.netbeans.lib.awtextra.AbsoluteConstraints(195, 138, 146, -1));

        bt_seleccionarParamedico.setText("Seleccionar");
        bt_seleccionarParamedico.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bt_seleccionarParamedicoMouseClicked(evt);
            }
        });
        jPanel8.add(bt_seleccionarParamedico, new org.netbeans.lib.awtextra.AbsoluteConstraints(378, 51, -1, -1));

        bt_reasignarParamedico.setText("Reasignar");
        bt_reasignarParamedico.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bt_reasignarParamedicoMouseClicked(evt);
            }
        });
        jPanel8.add(bt_reasignarParamedico, new org.netbeans.lib.awtextra.AbsoluteConstraints(378, 137, -1, -1));

        jLabel36.setIcon(new javax.swing.ImageIcon("/home/manuel/Documentos/estructuraDeDatos/Proyecto4_ED/Hospital_Escuela/Imagenes/image.php.png")); // NOI18N
        jPanel8.add(jLabel36, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 520, 250));

        jTabbedPane3.addTab("Paramedicos", jPanel8);

        jd_reasignacion.getContentPane().add(jTabbedPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, 529, -1));

        jLabel57.setIcon(new javax.swing.ImageIcon("/home/manuel/Documentos/estructuraDeDatos/Proyecto4_ED/Hospital_Escuela/Imagenes/dark_triangles_by_pixelperf3ct-d6tpizs.png")); // NOI18N
        jd_reasignacion.getContentPane().add(jLabel57, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 530, 300));

        jd_menuMapa.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        bt_addUbicaciones.setText("Agregar Ubicaciones");
        bt_addUbicaciones.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bt_addUbicacionesMouseClicked(evt);
            }
        });
        jd_menuMapa.getContentPane().add(bt_addUbicaciones, new org.netbeans.lib.awtextra.AbsoluteConstraints(97, 51, 199, 51));

        bt_addConexiones.setText("Agregar Conexiones");
        bt_addConexiones.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bt_addConexionesMouseClicked(evt);
            }
        });
        jd_menuMapa.getContentPane().add(bt_addConexiones, new org.netbeans.lib.awtextra.AbsoluteConstraints(97, 114, 199, 51));

        jLabel37.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        jLabel37.setForeground(new java.awt.Color(155, 11, 11));
        jLabel37.setText("Menu");
        jd_menuMapa.getContentPane().add(jLabel37, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 12, -1, -1));

        bt_dibujar.setText("Mostrar Mapa");
        bt_dibujar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bt_dibujarMouseClicked(evt);
            }
        });
        jd_menuMapa.getContentPane().add(bt_dibujar, new org.netbeans.lib.awtextra.AbsoluteConstraints(97, 183, 199, 42));

        jLabel48.setIcon(new javax.swing.ImageIcon("/home/manuel/Documentos/estructuraDeDatos/Proyecto4_ED/Hospital_Escuela/Imagenes/44-6600055.jpg")); // NOI18N
        jd_menuMapa.getContentPane().add(jLabel48, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 400, 300));

        jd_addUbicacion.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel9.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel9.add(cb_complejosMapa, new org.netbeans.lib.awtextra.AbsoluteConstraints(71, 63, 123, -1));

        jLabel39.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        jLabel39.setForeground(new java.awt.Color(155, 11, 11));
        jLabel39.setText("Complejos Hospitalarios");
        jPanel9.add(jLabel39, new org.netbeans.lib.awtextra.AbsoluteConstraints(59, 33, -1, -1));

        bt_addToMap.setText("Agregar");
        bt_addToMap.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bt_addToMapMouseClicked(evt);
            }
        });
        jPanel9.add(bt_addToMap, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 60, 144, -1));

        jLabel51.setIcon(new javax.swing.ImageIcon("/home/manuel/Documentos/estructuraDeDatos/Proyecto4_ED/Hospital_Escuela/Imagenes/dark_triangles_by_pixelperf3ct-d6tpizs.png")); // NOI18N
        jPanel9.add(jLabel51, new org.netbeans.lib.awtextra.AbsoluteConstraints(-3, 0, 370, 190));

        jTabbedPane4.addTab("Complejos Hospitalarios", jPanel9);

        jPanel10.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel40.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        jLabel40.setForeground(new java.awt.Color(155, 11, 11));
        jLabel40.setText("Nombre ");
        jPanel10.add(jLabel40, new org.netbeans.lib.awtextra.AbsoluteConstraints(59, 38, -1, -1));
        jPanel10.add(tf_nombreUbicacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(175, 28, 159, -1));
        jPanel10.add(tf_DireccionUbicacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(175, 96, 159, -1));

        bt_agregarUbi.setText("Agregar");
        bt_agregarUbi.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bt_agregarUbiMouseClicked(evt);
            }
        });
        jPanel10.add(bt_agregarUbi, new org.netbeans.lib.awtextra.AbsoluteConstraints(175, 160, -1, -1));

        jLabel41.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        jLabel41.setForeground(new java.awt.Color(155, 11, 11));
        jLabel41.setText("Direccion");
        jPanel10.add(jLabel41, new org.netbeans.lib.awtextra.AbsoluteConstraints(59, 101, -1, -1));

        jLabel52.setIcon(new javax.swing.ImageIcon("/home/manuel/Documentos/estructuraDeDatos/Proyecto4_ED/Hospital_Escuela/Imagenes/dark_triangles_by_pixelperf3ct-d6tpizs.png")); // NOI18N
        jPanel10.add(jLabel52, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 370, 190));

        jTabbedPane4.addTab("Ubicaciones Normales", jPanel10);

        jd_addUbicacion.getContentPane().add(jTabbedPane4, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 70, -1, -1));

        jLabel38.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        jLabel38.setForeground(new java.awt.Color(155, 11, 11));
        jLabel38.setText("Ubicaciones");
        jd_addUbicacion.getContentPane().add(jLabel38, new org.netbeans.lib.awtextra.AbsoluteConstraints(174, 21, -1, -1));

        jLabel50.setIcon(new javax.swing.ImageIcon("/home/manuel/Documentos/estructuraDeDatos/Proyecto4_ED/Hospital_Escuela/Imagenes/dark_triangles_by_pixelperf3ct-d6tpizs.png")); // NOI18N
        jd_addUbicacion.getContentPane().add(jLabel50, new org.netbeans.lib.awtextra.AbsoluteConstraints(-3, -5, 430, 320));

        jLabel49.setText("jLabel49");
        jd_addUbicacion.getContentPane().add(jLabel49, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 130, -1, 40));

        jd_conexiones.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel42.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        jLabel42.setForeground(new java.awt.Color(155, 11, 11));
        jLabel42.setText("Ubicaciones");
        jd_conexiones.getContentPane().add(jLabel42, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 69, -1, -1));

        jd_conexiones.getContentPane().add(cb_ubicacionesConexion, new org.netbeans.lib.awtextra.AbsoluteConstraints(52, 99, 112, -1));

        bt_seleccionarUbicacion.setText("Seleccionar");
        bt_seleccionarUbicacion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bt_seleccionarUbicacionMouseClicked(evt);
            }
        });
        jd_conexiones.getContentPane().add(bt_seleccionarUbicacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(252, 98, 97, -1));

        jLabel43.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        jLabel43.setForeground(new java.awt.Color(155, 11, 11));
        jLabel43.setText("Conexiones");
        jd_conexiones.getContentPane().add(jLabel43, new org.netbeans.lib.awtextra.AbsoluteConstraints(129, 12, -1, -1));

        jLabel44.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        jLabel44.setForeground(new java.awt.Color(155, 11, 11));
        jLabel44.setText("Distancia (km)");
        jd_conexiones.getContentPane().add(jLabel44, new org.netbeans.lib.awtextra.AbsoluteConstraints(44, 199, -1, -1));
        jd_conexiones.getContentPane().add(js_km, new org.netbeans.lib.awtextra.AbsoluteConstraints(192, 194, -1, -1));

        bt_crearConexion.setText("Crear");
        bt_crearConexion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bt_crearConexionMouseClicked(evt);
            }
        });
        jd_conexiones.getContentPane().add(bt_crearConexion, new org.netbeans.lib.awtextra.AbsoluteConstraints(253, 193, 96, -1));

        jLabel53.setIcon(new javax.swing.ImageIcon("/home/manuel/Documentos/estructuraDeDatos/Proyecto4_ED/Hospital_Escuela/Imagenes/dark_triangles_by_pixelperf3ct-d6tpizs.png")); // NOI18N
        jd_conexiones.getContentPane().add(jLabel53, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 400, 300));

        jd_emergencias.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel46.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        jLabel46.setForeground(new java.awt.Color(155, 11, 11));
        jLabel46.setText("Lugar Proveniente");
        jd_emergencias.getContentPane().add(jLabel46, new org.netbeans.lib.awtextra.AbsoluteConstraints(95, 83, -1, -1));

        jLabel45.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        jLabel45.setForeground(new java.awt.Color(155, 11, 11));
        jLabel45.setText("Emergencias");
        jd_emergencias.getContentPane().add(jLabel45, new org.netbeans.lib.awtextra.AbsoluteConstraints(221, 28, -1, -1));

        jd_emergencias.getContentPane().add(cb_lugarEmergencia, new org.netbeans.lib.awtextra.AbsoluteConstraints(95, 127, 134, -1));

        jLabel47.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        jLabel47.setForeground(new java.awt.Color(155, 11, 11));
        jLabel47.setText("Grado de emergencia");
        jd_emergencias.getContentPane().add(jLabel47, new org.netbeans.lib.awtextra.AbsoluteConstraints(328, 83, -1, -1));

        bt_sendEemergency.setText("Enviar emergencia");
        bt_sendEemergency.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bt_sendEemergencyMouseClicked(evt);
            }
        });
        jd_emergencias.getContentPane().add(bt_sendEemergency, new org.netbeans.lib.awtextra.AbsoluteConstraints(235, 202, -1, -1));

        cb_rankEemergencia.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "A", "B", "C", "D" }));
        jd_emergencias.getContentPane().add(cb_rankEemergencia, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 119, -1, -1));

        jLabel54.setIcon(new javax.swing.ImageIcon("/home/manuel/Documentos/estructuraDeDatos/Proyecto4_ED/Hospital_Escuela/Imagenes/dark_triangles_by_pixelperf3ct-d6tpizs.png")); // NOI18N
        jd_emergencias.getContentPane().add(jLabel54, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 570, 300));

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(155, 11, 11));
        jLabel3.setText("Hospital Escuela Universitario");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, -1, 50));

        bt_Gestionar.setBackground(java.awt.Color.gray);
        bt_Gestionar.setForeground(new java.awt.Color(155, 11, 11));
        bt_Gestionar.setText("Gestionar Recursos");
        bt_Gestionar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bt_GestionarMouseClicked(evt);
            }
        });
        getContentPane().add(bt_Gestionar, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 50, 240, 110));

        bt_mapa.setBackground(java.awt.Color.gray);
        bt_mapa.setForeground(new java.awt.Color(155, 11, 11));
        bt_mapa.setText("Mapa de La Ciudad");
        bt_mapa.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bt_mapaMouseClicked(evt);
            }
        });
        getContentPane().add(bt_mapa, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 180, 240, 110));

        bt_emergencias.setBackground(java.awt.Color.gray);
        bt_emergencias.setForeground(new java.awt.Color(155, 11, 11));
        bt_emergencias.setText("Gestion de Emergencias");
        bt_emergencias.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bt_emergenciasMouseClicked(evt);
            }
        });
        getContentPane().add(bt_emergencias, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 310, 240, 110));

        jLabel1.setIcon(new javax.swing.ImageIcon("/home/manuel/Documentos/estructuraDeDatos/Proyecto4_ED/Hospital_Escuela/Imagenes/dark_triangles_by_pixelperf3ct-d6tpizs.png")); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -40, 750, 500));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bt_GestionarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt_GestionarMouseClicked
        showDialog(this.jd_gestionRecursos);
    }//GEN-LAST:event_bt_GestionarMouseClicked

    private void jButton4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton4MouseClicked
        this.jd_gestionRecursos.setVisible(false);
        showDialog(this.jd_creacion);
    }//GEN-LAST:event_jButton4MouseClicked

    private void jButton5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton5MouseClicked
        this.jd_gestionRecursos.setVisible(false);
        this.listInComboBox(hospitales, this.cb_eliminarComplejos);
        this.ambulanciaInComboBox(ambulancias, this.cb_eliminarAmbulancias);
        this.paramedicoInComboBox(paramedicos, this.cb_eliminarParamedicos);
        showDialog(this.jd_eliminacion);
    }//GEN-LAST:event_jButton5MouseClicked

    private void jButton6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton6MouseClicked
        this.jd_gestionRecursos.setVisible(false);
        this.listInComboBox(hospitales, this.cb_complejosA);
        this.listInComboBox(hospitales, this.cb_complejosP);
        this.ambulanciaInComboBox(ambulancias, this.cb_seleccionarAmbulancia);
        this.paramedicoInComboBox(paramedicos, this.cb_seleccionarParamedicos);
        showDialog(this.jd_reasignacion);
    }//GEN-LAST:event_jButton6MouseClicked

    private void bt_crearHospitalMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt_crearHospitalMouseClicked
        String nombre;
        String direccion;
        int maxParamedicos;
        int maxAmbulancias;
        String ranking;
        boolean seguir = true;

        nombre = this.tf_nombreHospital.getText();
        direccion = this.tf_direccionHospital.getText();
        maxParamedicos = Integer.parseInt(this.js_maxParamedicosHosp.getValue().toString());
        maxAmbulancias = Integer.parseInt(this.js_maxAmbulanciasHosp.getValue().toString());
        ranking = this.cb_rankingHospital.getSelectedItem().toString();

        int num = getRanking(ranking);
        Emergencia emergencia = Emergencia.A;

        if (num == 4) {
            emergencia = Emergencia.A;
        } else if (num == 3) {
            emergencia = Emergencia.B;
        } else if (num == 2) {
            emergencia = Emergencia.C;
        } else if (num == 1) {
            emergencia = Emergencia.D;
        }
        for (int i = 0; i < hospitales.size(); i++) {
            if (hospitales.get(i).getNombre() == nombre) {
                seguir = false;
            }
        }

        if (seguir) {
            hospitales.add(new Hospital(maxParamedicos, maxAmbulancias, emergencia, nombre, direccion));
            JOptionPane.showMessageDialog(this, "Hospital creado con exito", "Atencion", JOptionPane.INFORMATION_MESSAGE);
        } else {
            JOptionPane.showMessageDialog(this, "No se pueden crear dos hospitales con el mismp nombre", "Atencion", JOptionPane.INFORMATION_MESSAGE);
        }
        this.tf_nombreHospital.setText("");
        this.tf_direccionHospital.setText("");
        this.js_maxParamedicosHosp.setValue(0);
        this.js_maxAmbulanciasHosp.setValue(0);
        listInComboBox(hospitales, this.cb_complejosAmbulancia);
        listInComboBox(hospitales, this.cb_complejoParamedico);
    }//GEN-LAST:event_bt_crearHospitalMouseClicked

    private void jTabbedPane1StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jTabbedPane1StateChanged
        listInComboBox(hospitales, this.cb_complejosAmbulancia);
        listInComboBox(hospitales, this.cb_complejoParamedico);
    }//GEN-LAST:event_jTabbedPane1StateChanged

    private void bt_crearAmbulanciaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt_crearAmbulanciaMouseClicked
        String placa;
        String año;
        double velocidad;
        Hospital temporal = new Hospital();

        placa = this.tf_placaAmbulancia.getText();
        año = this.tf_año_ambulancia.getText();
        velocidad = Double.parseDouble(this.tf_speedAmbulancia.getText());
        temporal = (Hospital) this.cb_complejosAmbulancia.getSelectedItem();

        if (temporal.getAmbulancias().size() < temporal.getMaxAmbulancias()) {
            ambulancias.add(new Ambulancia(placa, año, velocidad, temporal));
            temporal.addAmbulancia(ambulancias.get(ambulancias.size() - 1));
            JOptionPane.showMessageDialog(this, "Ambulancia creada con exito", "Atencion", JOptionPane.INFORMATION_MESSAGE);
        } else {
            JOptionPane.showMessageDialog(this, "Ya no hay lugar para mas ambulancias en el hospital", "ERROR!!!", JOptionPane.ERROR_MESSAGE);
        }
        this.tf_año_ambulancia.setText("");
        this.tf_placaAmbulancia.setText("");
        this.tf_speedAmbulancia.setText("");
    }//GEN-LAST:event_bt_crearAmbulanciaMouseClicked

    private void jButton7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton7MouseClicked
        String nombre;
        int edad;
        String id;
        String ranking;
        int num;
        Hospital temporal = new Hospital();

        nombre = this.tf_nombreParamedico.getText();
        edad = Integer.parseInt(this.tf_edadParamedico.getText());
        id = this.tf_idParamedico.getText();
        ranking = this.cb_rankingParamedico.getSelectedItem().toString();
        temporal = (Hospital) this.cb_complejoParamedico.getSelectedItem();

        num = getRanking(ranking);
        Emergencia emergencia = Emergencia.A;

        if (num == 4) {
            emergencia = Emergencia.A;
        } else if (num == 3) {
            emergencia = Emergencia.B;
        } else if (num == 2) {
            emergencia = Emergencia.C;
        } else if (num == 1) {
            emergencia = Emergencia.D;
        }

        if (temporal.getParamedicos().size() < temporal.getMaxParamedicos()) {
            paramedicos.add(new Paramedico(nombre, edad, id, emergencia, temporal));
            temporal.addParamedico(paramedicos.get(paramedicos.size() - 1));
            JOptionPane.showMessageDialog(this, "Paramedico creado con exito", "Atencion", JOptionPane.INFORMATION_MESSAGE);
        } else {
            JOptionPane.showMessageDialog(this, "No hay lugar para mas paramedicos en el hospital", "ERROR", JOptionPane.ERROR_MESSAGE);
        }

        this.tf_nombreParamedico.setText("");
        this.tf_edadParamedico.setText("");
        this.tf_idParamedico.setText("");
    }//GEN-LAST:event_jButton7MouseClicked

    private void bt_eliminarComplejosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt_eliminarComplejosMouseClicked
        hospitalTemporal = (Hospital) this.cb_eliminarComplejos.getSelectedItem();
        hospitales.remove(hospitalTemporal);
        for (Node nodo : mapa.getEachNode()) {
            if (hospitalTemporal.getNombre().equals(nodo.getId())) {
                mapa.removeNode(hospitalTemporal.getNombre());
            }
        }
        listInComboBox(hospitales, this.cb_eliminarComplejos);
        JOptionPane.showMessageDialog(this, "Hospital eliminado con exito", "Atencion", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_bt_eliminarComplejosMouseClicked

    private void jTabbedPane2StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jTabbedPane2StateChanged
        this.listInComboBox(hospitales, this.cb_eliminarComplejos);
        this.ambulanciaInComboBox(ambulancias, this.cb_eliminarAmbulancias);
        this.paramedicoInComboBox(paramedicos, this.cb_eliminarParamedicos);
    }//GEN-LAST:event_jTabbedPane2StateChanged

    private void bt_eliminarAmbulacniasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt_eliminarAmbulacniasMouseClicked
        ambulanciaTemporal = (Ambulancia) this.cb_eliminarAmbulancias.getSelectedItem();
        ambulanciaTemporal.getComplejo().getAmbulancias().remove(ambulanciaTemporal);
        ambulancias.remove(ambulanciaTemporal);
        this.ambulanciaInComboBox(ambulancias, this.cb_eliminarAmbulancias);
        JOptionPane.showMessageDialog(this, "Ambulancia eliminada con exito", "Atencion", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_bt_eliminarAmbulacniasMouseClicked

    private void bt_eliminarParamedicosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt_eliminarParamedicosMouseClicked
        paramedicoTemporal = (Paramedico) this.cb_eliminarParamedicos.getSelectedItem();
        paramedicoTemporal.getComplejo().getParamedicos().remove(paramedicoTemporal);
        paramedicos.remove(paramedicoTemporal);
        this.paramedicoInComboBox(paramedicos, this.cb_eliminarParamedicos);
        JOptionPane.showMessageDialog(this, "Paramedico eliminado con exito", "Atencion", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_bt_eliminarParamedicosMouseClicked

    private void jTabbedPane3StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jTabbedPane3StateChanged
        this.listInComboBox(hospitales, this.cb_complejosA);
        this.listInComboBox(hospitales, this.cb_complejosP);
        this.ambulanciaInComboBox(ambulancias, this.cb_seleccionarAmbulancia);
        this.paramedicoInComboBox(paramedicos, this.cb_seleccionarParamedicos);
    }//GEN-LAST:event_jTabbedPane3StateChanged

    private void bt_seleccionarAmbulanciaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt_seleccionarAmbulanciaMouseClicked
        ambulanciaTemporal = (Ambulancia) this.cb_seleccionarAmbulancia.getSelectedItem();
        contador1++;
        JOptionPane.showMessageDialog(this, "Ambulancia seleccionada con exito", "Atencion", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_bt_seleccionarAmbulanciaMouseClicked

    private void bt_reasignarAmbulanciaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt_reasignarAmbulanciaMouseClicked
        if (contador1 == 1) {
            hospitalTemporal = (Hospital) this.cb_complejosA.getSelectedItem();

            if (hospitalTemporal.getAmbulancias().size() < hospitalTemporal.getMaxAmbulancias()) {
                ambulanciaTemporal.getComplejo().getAmbulancias().remove(ambulanciaTemporal);
                ambulanciaTemporal.setComplejo(hospitalTemporal);
                hospitalTemporal.addAmbulancia(ambulanciaTemporal);
                contador1 = 0;
                JOptionPane.showMessageDialog(this, "Ambulancia reasignada con exito", "Atencion", JOptionPane.INFORMATION_MESSAGE);
            } else {
                contador1 = 0;
                JOptionPane.showMessageDialog(this, "Error en la reasignacion", "Atencion", JOptionPane.ERROR_MESSAGE);
            }
        } else {
            JOptionPane.showMessageDialog(this, "Necesita seleccionar una ambulancia", "Atencion", JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_bt_reasignarAmbulanciaMouseClicked

    private void bt_seleccionarParamedicoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt_seleccionarParamedicoMouseClicked
        paramedicoTemporal = (Paramedico) this.cb_seleccionarParamedicos.getSelectedItem();
        contador2++;
        JOptionPane.showMessageDialog(this, "Paramedico seleccionado con exito", "Atencion", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_bt_seleccionarParamedicoMouseClicked

    private void bt_reasignarParamedicoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt_reasignarParamedicoMouseClicked
        if (contador2 == 1) {
            hospitalTemporal = (Hospital) this.cb_complejosP.getSelectedItem();

            if (hospitalTemporal.getParamedicos().size() < hospitalTemporal.getMaxParamedicos()) {
                paramedicoTemporal.getComplejo().getParamedicos().remove(paramedicoTemporal);
                paramedicoTemporal.setComplejo(hospitalTemporal);
                hospitalTemporal.addParamedico(paramedicoTemporal);
                contador2 = 0;
                JOptionPane.showMessageDialog(this, "Paramedico reasignado con exito", "Atencion", JOptionPane.INFORMATION_MESSAGE);
            } else {
                JOptionPane.showMessageDialog(this, "Error en la reasignacion", "Atencion", JOptionPane.ERROR_MESSAGE);
                contador2 = 0;
            }
        } else {
            JOptionPane.showMessageDialog(this, "Necesita seleccionar un paramedico", "Atencion", JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_bt_reasignarParamedicoMouseClicked

    private void bt_mapaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt_mapaMouseClicked
        this.showDialog(jd_menuMapa);
    }//GEN-LAST:event_bt_mapaMouseClicked

    private void bt_addUbicacionesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt_addUbicacionesMouseClicked
        this.jd_menuMapa.setVisible(false);
        listInComboBox(hospitales, this.cb_complejosMapa);
        DefaultComboBoxModel modelo = new DefaultComboBoxModel();
        modelo = (DefaultComboBoxModel) this.cb_complejosMapa.getModel();
        for (int i = 0; i < ubicaciones.size(); i++) {
            modelo.addElement(ubicaciones.get(i));
        }
        this.cb_complejosMapa.setModel(modelo);
        this.showDialog(this.jd_addUbicacion);
    }//GEN-LAST:event_bt_addUbicacionesMouseClicked

    private void bt_addToMapMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt_addToMapMouseClicked
        ubicacionTemporal = (Ubicacion) this.cb_complejosMapa.getSelectedItem();
        boolean seguir = true;

        for (Node nodo : mapa.getEachNode()) {
            if (nodo.getId() == ubicacionTemporal.getNombre()) {
                seguir = false;
            }
        }
        if (seguir) {
            mapa.addNode(ubicacionTemporal.getNombre()).addAttribute("label", ubicacionTemporal.getNombre());
            JOptionPane.showMessageDialog(this, "Nodo agregado exitosamente");
        } else {
            JOptionPane.showMessageDialog(this, "Este nodo ya ha sido agregado");
        }
    }//GEN-LAST:event_bt_addToMapMouseClicked

    private void bt_agregarUbiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt_agregarUbiMouseClicked
        String nombre;
        String direccion;
        boolean seguir = true;

        nombre = this.tf_nombreUbicacion.getText();
        direccion = this.tf_DireccionUbicacion.getText();

        for (Node nodo : mapa.getEachNode()) {
            if (nodo.getId().equals(nombre)) {
                seguir = false;
            }
        }

        if (seguir) {
            ubicaciones.add(new Ubicacion(nombre, direccion));
            mapa.addNode(nombre).addAttribute("label", nombre);
            JOptionPane.showMessageDialog(this, "Ubicacion agregada exitosamente");
        } else {
            JOptionPane.showMessageDialog(this, "NO pueden existir dos ubicaciones con el mismo nombre");
        }

        this.tf_DireccionUbicacion.setText("");
        this.tf_nombreUbicacion.setText("");
    }//GEN-LAST:event_bt_agregarUbiMouseClicked

    private void bt_dibujarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt_dibujarMouseClicked
        mapa.display();
    }//GEN-LAST:event_bt_dibujarMouseClicked

    private void bt_seleccionarUbicacionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt_seleccionarUbicacionMouseClicked
        if (contadorNodos < 2) {
            ubicacionesTemporales.add((Ubicacion) this.cb_ubicacionesConexion.getSelectedItem());
            contadorNodos++;
            JOptionPane.showMessageDialog(this, "Ubicacion seleccionada correctamente");
        } else {
            JOptionPane.showMessageDialog(this, "Ya hay dos ubicaciones seleccionadad");
        }
    }//GEN-LAST:event_bt_seleccionarUbicacionMouseClicked

    private void bt_crearConexionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt_crearConexionMouseClicked
        if (contadorNodos == 2) {
            mapa.addEdge(id + "", ubicacionesTemporales.get(0).getNombre(), ubicacionesTemporales.get(1).getNombre()).addAttribute("length",
                    Double.parseDouble(this.js_km.getValue().toString()));
            mapa.getEdge(id + "").addAttribute("label", Double.parseDouble(this.js_km.getValue().toString()));
            id++;
            contadorNodos = 0;
            ubicacionesTemporales = new ArrayList();
            JOptionPane.showMessageDialog(this, "Conexion creada exitosamente");
        } else {
            JOptionPane.showMessageDialog(this, "Numero erroneo de nodos para esta operacion, vuelva a selecionar");
        }
    }//GEN-LAST:event_bt_crearConexionMouseClicked

    private void bt_addConexionesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt_addConexionesMouseClicked
        this.jd_menuMapa.setVisible(false);
        ArrayList<Object> temporal = new ArrayList();
        for (int i = 0; i < hospitales.size(); i++) {
            for (Node nodo : mapa.getEachNode()) {
                if (nodo.getId() == hospitales.get(i).getNombre()) {
                    temporal.add(hospitales.get(i));
                }
            }
        }
        for (int i = 0; i < ubicaciones.size(); i++) {
            for (Node nodo : mapa.getEachNode()) {
                if (nodo.getId() == ubicaciones.get(i).getNombre()) {
                    temporal.add(ubicaciones.get(i));
                }
            }
        }

        DefaultComboBoxModel modelo = new DefaultComboBoxModel();
        for (int i = 0; i < temporal.size(); i++) {
            modelo.addElement(temporal.get(i));
        }
        this.cb_ubicacionesConexion.setModel(modelo);
        this.showDialog(this.jd_conexiones);
    }//GEN-LAST:event_bt_addConexionesMouseClicked

    private void bt_sendEemergencyMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt_sendEemergencyMouseClicked
        Ubicacion lugar = new Ubicacion();
        Emergencia ranking = Emergencia.D;
        ArrayList<Hospital> temporal = new ArrayList();

        for (int i = 0; i < hospitales.size(); i++) {
            for (Node nodo : mapa.getEachNode()) {
                if (nodo.getId() == hospitales.get(i).getNombre()) {
                    temporal.add(hospitales.get(i));
                }
            }
        }
        if (this.cb_rankEemergencia.getSelectedItem().toString() == "A") {
            ranking = Emergencia.A;
        } else if (this.cb_rankEemergencia.getSelectedItem().toString() == "B") {
            ranking = Emergencia.B;
        } else if (this.cb_rankEemergencia.getSelectedItem().toString() == "C") {
            ranking = Emergencia.C;
        } else if (this.cb_rankEemergencia.getSelectedItem().toString() == "D") {
            ranking = Emergencia.D;
        }

        lugar = (Ubicacion) this.cb_lugarEmergencia.getSelectedItem();
        Caso emergencia = new Caso(ranking, lugar, lugar.getNombre(), mapa, temporal);
        emergencia.start();
    }//GEN-LAST:event_bt_sendEemergencyMouseClicked

    private void bt_emergenciasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt_emergenciasMouseClicked
        if (mapa.getEdgeCount() >= mapa.getNodeCount() - 1) {
            DefaultComboBoxModel modelo = new DefaultComboBoxModel();
            for (int i = 0; i < this.ubicaciones.size(); i++) {
                for (Node nodo : mapa.getEachNode()) {
                    if (nodo.getId() == ubicaciones.get(i).getNombre()) {
                        modelo.addElement(ubicaciones.get(i));
                    }
                }

            }
            this.cb_lugarEmergencia.setModel(modelo);
            showDialog(this.jd_emergencias);
        } else {
            JOptionPane.showMessageDialog(this, "Todos sus nodos deben estar conectados para esta funcion");
        }
    }//GEN-LAST:event_bt_emergenciasMouseClicked

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        this.guardar();
    }//GEN-LAST:event_formWindowClosing

    public boolean verifificarNombre(ArrayList<Ubicacion> lista, String nombre) {
        boolean seguir = true;
        for (int i = 0; i < lista.size(); i++) {
            if (lista.get(i).getNombre() == nombre) {
                seguir = false;
            }
        }
        return seguir;
    }

    public void cargar() {
        File archivo = null;
        try {
            archivo = new File("./listas.mp");
            FileInputStream fi = new FileInputStream(archivo);
            ObjectInputStream oi = new ObjectInputStream(fi);
            listaGeneral = (Listas) oi.readObject();
            hospitales = listaGeneral.getHospitales();
            ambulancias = listaGeneral.getAmbulancias();
            paramedicos = listaGeneral.getParamedicos();
            ubicaciones = listaGeneral.getUbicaciones();
            oi.close();
            fi.close();
        } catch (Exception e) {
        }
    }

    public void guardar() {
        this.listaGeneral = new Listas(hospitales, ambulancias, ubicaciones, paramedicos);
        File archivo = null;
        try {
            archivo = new File("./listas.mp");
            FileOutputStream fo = new FileOutputStream(archivo);
            ObjectOutputStream oo = new ObjectOutputStream(fo);
            oo.writeObject(listaGeneral);
            oo.close();
            fo.close();
            JOptionPane.showMessageDialog(this, "Se ha guardado la informacion con exito");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error al guardar");
        }
    }

    public void listInComboBox(ArrayList<Hospital> lista, JComboBox box) {
        DefaultComboBoxModel modelo = new DefaultComboBoxModel();
        for (int i = 0; i < lista.size(); i++) {
            modelo.addElement(lista.get(i));
        }
        box.setModel(modelo);
    }

    public void ambulanciaInComboBox(ArrayList<Ambulancia> lista, JComboBox box) {
        DefaultComboBoxModel modelo = new DefaultComboBoxModel();
        for (int i = 0; i < lista.size(); i++) {
            modelo.addElement(lista.get(i));
        }
        box.setModel(modelo);
    }

    public void paramedicoInComboBox(ArrayList<Paramedico> lista, JComboBox box) {
        DefaultComboBoxModel modelo = new DefaultComboBoxModel();
        for (int i = 0; i < lista.size(); i++) {
            modelo.addElement(lista.get(i));
        }
        box.setModel(modelo);
    }

    public void showDialog(JDialog ventana) {
        ventana.pack();
        ventana.setLocationRelativeTo(this);
        ventana.setVisible(true);
    }

    public int getRanking(String letra) {

        if (letra == "A") {
            return 4;
        } else if (letra == "B") {
            return 3;
        } else if (letra == "C") {
            return 2;
        } else if (letra == "D") {
            return 1;
        }
        return -1;
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bt_Gestionar;
    private javax.swing.JButton bt_addConexiones;
    private javax.swing.JButton bt_addToMap;
    private javax.swing.JButton bt_addUbicaciones;
    private javax.swing.JButton bt_agregarUbi;
    private javax.swing.JButton bt_crearAmbulancia;
    private javax.swing.JButton bt_crearConexion;
    private javax.swing.JButton bt_crearHospital;
    private javax.swing.JButton bt_dibujar;
    private javax.swing.JButton bt_eliminarAmbulacnias;
    private javax.swing.JButton bt_eliminarComplejos;
    private javax.swing.JButton bt_eliminarParamedicos;
    private javax.swing.JButton bt_emergencias;
    private javax.swing.JButton bt_mapa;
    private javax.swing.JButton bt_reasignarAmbulancia;
    private javax.swing.JButton bt_reasignarParamedico;
    private javax.swing.JButton bt_seleccionarAmbulancia;
    private javax.swing.JButton bt_seleccionarParamedico;
    private javax.swing.JButton bt_seleccionarUbicacion;
    private javax.swing.JButton bt_sendEemergency;
    private javax.swing.JComboBox cb_complejoParamedico;
    private javax.swing.JComboBox cb_complejosA;
    private javax.swing.JComboBox cb_complejosAmbulancia;
    private javax.swing.JComboBox cb_complejosMapa;
    private javax.swing.JComboBox cb_complejosP;
    private javax.swing.JComboBox cb_eliminarAmbulancias;
    private javax.swing.JComboBox cb_eliminarComplejos;
    private javax.swing.JComboBox cb_eliminarParamedicos;
    private javax.swing.JComboBox cb_lugarEmergencia;
    private javax.swing.JComboBox cb_rankEemergencia;
    private javax.swing.JComboBox cb_rankingHospital;
    private javax.swing.JComboBox cb_rankingParamedico;
    private javax.swing.JComboBox cb_seleccionarAmbulancia;
    private javax.swing.JComboBox cb_seleccionarParamedicos;
    private javax.swing.JComboBox cb_ubicacionesConexion;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel43;
    private javax.swing.JLabel jLabel44;
    private javax.swing.JLabel jLabel45;
    private javax.swing.JLabel jLabel46;
    private javax.swing.JLabel jLabel47;
    private javax.swing.JLabel jLabel48;
    private javax.swing.JLabel jLabel49;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel50;
    private javax.swing.JLabel jLabel51;
    private javax.swing.JLabel jLabel52;
    private javax.swing.JLabel jLabel53;
    private javax.swing.JLabel jLabel54;
    private javax.swing.JLabel jLabel55;
    private javax.swing.JLabel jLabel56;
    private javax.swing.JLabel jLabel57;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTabbedPane jTabbedPane2;
    private javax.swing.JTabbedPane jTabbedPane3;
    private javax.swing.JTabbedPane jTabbedPane4;
    private javax.swing.JDialog jd_addUbicacion;
    private javax.swing.JDialog jd_conexiones;
    private javax.swing.JDialog jd_creacion;
    private javax.swing.JDialog jd_eliminacion;
    private javax.swing.JDialog jd_emergencias;
    private javax.swing.JDialog jd_gestionRecursos;
    private javax.swing.JDialog jd_menuMapa;
    private javax.swing.JDialog jd_reasignacion;
    private javax.swing.JSpinner js_km;
    private javax.swing.JSpinner js_maxAmbulanciasHosp;
    private javax.swing.JSpinner js_maxParamedicosHosp;
    private javax.swing.JTextField tf_DireccionUbicacion;
    private javax.swing.JTextField tf_año_ambulancia;
    private javax.swing.JTextField tf_direccionHospital;
    private javax.swing.JTextField tf_edadParamedico;
    private javax.swing.JTextField tf_idParamedico;
    private javax.swing.JTextField tf_nombreHospital;
    private javax.swing.JTextField tf_nombreParamedico;
    private javax.swing.JTextField tf_nombreUbicacion;
    private javax.swing.JTextField tf_placaAmbulancia;
    private javax.swing.JTextField tf_speedAmbulancia;
    // End of variables declaration//GEN-END:variables
    ArrayList<Hospital> hospitales = new ArrayList();
    ArrayList<Ambulancia> ambulancias = new ArrayList();
    ArrayList<Paramedico> paramedicos = new ArrayList();
    ArrayList<Ubicacion> ubicaciones = new ArrayList();
    Hospital hospitalTemporal = new Hospital();
    Paramedico paramedicoTemporal = new Paramedico();
    Ubicacion ubicacionTemporal = new Ubicacion();
    Ambulancia ambulanciaTemporal = new Ambulancia();
    int contador1 = 0;
    int contador2 = 0;
    Graph mapa = new SingleGraph("Nodo Principal");
    int contadorNodos = 0;
    ArrayList<Ubicacion> ubicacionesTemporales = new ArrayList();
    int id = 0;
    Listas listaGeneral = new Listas();
}
